### ISSUE TITLE
createThread base64 方法编译生成EXE的时候会报错

### ISSUE THREAD

**Issue by Chinakentgao** [safe6Sec/GolangBypassAV#6]
panic: exit status 1

goroutine 1 [running]:
main.main()
        F:/GolangBypassAV-master/gen/main.go:271 +0xe05

**Comment by safe6Sec** [comment]
近期会有次大更新

**Comment by safe6Sec** [comment]
> panic: exit status 1
> 
> goroutine 1 [running]: main.main() F:/GolangBypassAV-master/gen/main.go:271 +0xe05

ok
